name: CI

on: [push]
 
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        version: ['3.90']
    steps:
    - name: Checkout nopCommerce repo
      uses: actions/checkout@v2
      with:
        repository: nopSolutions/nopCommerce
        ref: 'release-${{ matrix.version }}'
    
    - name: Checkout plugin repo
      uses: actions/checkout@v2
      with:
        path: src\Plugins\Nop.Plugin.Misc.ComingSoonPage\
        ref: '${{ matrix.version }}'
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Restore packages
      run: nuget restore src\NopCommerce.sln
    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: Build plugin with MSBuild
      run: msbuild src\Plugins\Nop.Plugin.Misc.ComingSoonPage\Nop.Plugin.Misc.ComingSoonPage.csproj -p:Configuration=Release
    
    - run: Xcopy /E /I src\Plugins\Nop.Plugin.Misc.ComingSoonPage\ReleaseFiles artifact
    - run: Xcopy /E /I src\Presentation\Nop.Web\Plugins\Misc.ComingSoonPage "artifact\ComingSoonPage\nopCommerce ${{ matrix.version }}\Misc.ComingSoonPage"
    - run: Xcopy /E /I src\Plugins\Nop.Plugin.Misc.ComingSoonPage "artifact\ComingSoonPage\nopCommerce ${{ matrix.version }}\Nop.Plugin.Misc.ComingSoonPage"
    
    - uses: actions/upload-artifact@v1
      with:
        name: ComingSoonPage
        path: artifact
