name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        args:
          - { version : '4.00', tag : '4.00.1'}
          - { version : '4.10', tag : '4.10.1', dotnet : '2.1'}
          - { version : '4.20', tag : '4.20.1', dotnet : '2.2'}
          - { version : '4.30', tag : '4.30.1', dotnet : '3.1'}
          - { version : '4.40', tag : '4.40', dotnet : '3.1'}
    steps:
    - name: Checkout nopCommerce repo
      uses: actions/checkout@v2
      with:
        repository: nopSolutions/nopCommerce
        ref: 'release-${{ matrix.args.version }}'

    - name: Checkout plugin repo
      uses: actions/checkout@v2
      with:
        path: src\Plugins\Nop.Plugin.Misc.ComingSoonPage\
        ref: '${{ matrix.args.tag }}'

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1

    - name: Restore packages
      run: nuget restore src\NopCommerce.sln

    - name: Restore packages
      run: nuget restore src\Plugins\Nop.Plugin.Misc.ComingSoonPage\Nop.Plugin.Misc.ComingSoonPage.csproj

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1
      if: matrix.args.version <= '4.00'

    - name: Build plugin with MSBuild
      run: msbuild src\Plugins\Nop.Plugin.Misc.ComingSoonPage\Nop.Plugin.Misc.ComingSoonPage.csproj -p:Configuration=Release
      if: matrix.args.version <= '4.00'

    - name: Setup dotnet build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{matrix.args.dotnet}}.x'
      if: matrix.args.version > '4.00'

    - name: Build plugin with dotnet
      run: dotnet build src\Plugins\Nop.Plugin.Misc.ComingSoonPage\Nop.Plugin.Misc.ComingSoonPage.csproj -p:Configuration=Release
      if: matrix.args.version > '4.00'

    - run: Xcopy /E /I src\Plugins\Nop.Plugin.Misc.ComingSoonPage\ReleaseFiles artifact
    - run: Xcopy /E /I src\Presentation\Nop.Web\Plugins\Misc.ComingSoonPage "artifact\ComingSoonPage\nopCommerce ${{ matrix.args.version }}\Misc.ComingSoonPage"
    - run: Xcopy /E /I src\Plugins\Nop.Plugin.Misc.ComingSoonPage "artifact\ComingSoonPage\nopCommerce ${{ matrix.args.version }}\Nop.Plugin.Misc.ComingSoonPage"

    - uses: actions/upload-artifact@v1
      with:
        name: ComingSoonPage
        path: artifact
